// exports/dashboard-products-completo-20260219-143558/comercio-plus-frontend/src/components/ui/button.tsx
﻿import type { ButtonHTMLAttributes, ReactNode } from 'react'

const variants = {
  primary:
    'border border-transparent bg-[#FF6B35] text-white hover:-translate-y-[2px] hover:bg-[#E65A2B] hover:shadow-[0_8px_20px_rgba(255,107,53,0.3)]',
  secondary:
    'border border-transparent bg-[#004E89] text-white hover:bg-[#003f6f]',
  outline:
    'border-2 border-[#D1D5DB] bg-transparent text-[#1F2937] hover:border-[#FF6B35] hover:text-[#FF6B35]',
  ghost:
    'border border-transparent bg-transparent text-[#4B5563] hover:bg-[#F3F4F6] hover:text-[#1F2937]',
  danger:
    'border border-transparent bg-[#EF476F] text-white hover:bg-[#d83f65]',
} as const

export type ButtonVariant = keyof typeof variants

const baseButtonClasses =
  'inline-flex items-center justify-center gap-2 rounded-[8px] px-6 py-3 text-[15px] font-medium transition-all duration-300 ease-in-out focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#FF6B35]/30'

type Props = ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: ButtonVariant
  loading?: boolean
  children: ReactNode
}

export const buttonVariants = (variant: ButtonVariant = 'primary', className = '') =>
  `${baseButtonClasses} ${variants[variant]} disabled:cursor-not-allowed disabled:opacity-50 ${className}`.trim()

export default function Button({
  variant = 'primary',
  loading = false,
  className = '',
  children,
  ...props
}: Props) {
  return (
    <button
      className={buttonVariants(variant, className)}
      disabled={loading || props.disabled}
      {...props}
    >
      {children}
    </button>
  )
}

// resources/js/components/ui/Button.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '../lib/utils'

const buttonVariants = cva(
  'inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive:
          'bg-destructive text-destructive-foreground hover:bg-destructive/90',
        outline:
          'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
        secondary:
          'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-10 px-4 py-2',
        sm: 'h-9 rounded-md px-3',
        lg: 'h-11 rounded-md px-8',
        icon: 'h-10 w-10',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
)

interface ButtonProps extends VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'default',
  size: 'default',
  asChild: false,
})

const emit = defineEmits<{
  click: []
}>()

const buttonClasses = computed(() =>
  cn(buttonVariants({
    variant: props.variant,
    size: props.size,
  }))
)

const handleClick = () => {
  emit('click')
}
</script>

<template>
  <button
    :class="buttonClasses"
    @click="handleClick"
  >
    <slot />
  </button>
</template>
