// app/src/components/header.tsx
import Link from "next/link";
import { Logo } from "./logo";
import { AuthWidget } from "./auth-widget";

export function Header() {
  return (
    <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container h-16 flex items-center justify-between">
        <div className="flex items-center gap-6">
          <Link href="/" className="flex items-center gap-2">
            <Logo />
          </Link>
        </div>

        <div className="flex items-center">
          <AuthWidget />
        </div>
      </div>
    </header>
  );
}

// frontend/src/components/Header.vue
<template>
  <header class="sticky top-0 z-50 w-full border-b bg-background/80 backdrop-blur-sm">
    <div class="container h-16 flex items-center justify-between">
      <div class="flex items-center gap-6">
        <router-link to="/" class="flex items-center gap-2">
          <Logo />
        </router-link>
      </div>

      <nav class="hidden md:flex items-center gap-4">
        <router-link to="/dashboard" class="text-sm font-medium text-muted-foreground hover:text-primary transition-colors">Panel</router-link>
        <router-link to="/#stores" class="text-sm font-medium text-muted-foreground hover:text-primary transition-colors">Tiendas</router-link>
      </nav>

      <div class="flex items-center">
        <AuthWidget />
      </div>
    </div>
  </header>
</template>

<script setup>
import Logo from './Logo.vue';
import AuthWidget from './AuthWidget.vue';
</script>

<style scoped>
/* Puedes agregar estilos específicos para el Header aquí */
</style>
