// resources/js/Pages/Products/Index.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black">
    <!-- Header moderno con diseño JBL -->
    <header class="sticky top-0 z-50 bg-black/80 backdrop-blur-xl border-b border-white/10 shadow-2xl">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center h-16">
          <RouterLink class="flex items-center space-x-3" to="/">
            <div class="w-10 h-10 bg-gradient-to-r from-orange-500 to-red-600 rounded-xl flex items-center justify-center">
              <span class="text-white font-bold text-lg">C</span>
            </div>
            <div class="flex flex-col">
              <span class="text-xl font-bold text-white">ComercioPlus</span>
              <span class="text-xs text-gray-400">Repuestos & Accesorios</span>
            </div>
          </RouterLink>

          <div class="flex items-center space-x-4">
            <RouterLink
              class="text-gray-300 hover:text-orange-400 px-4 py-2 rounded-lg transition-colors border border-white/10 hover:border-orange-400/30"
              to="/dashboard"
            >
              Dashboard
            </RouterLink>
            <RouterLink
              class="bg-gradient-to-r from-orange-500 to-red-600 text-white px-6 py-2 rounded-xl font-medium hover:shadow-2xl hover:shadow-orange-500/25 transition-all duration-500 transform hover:scale-105 flex items-center space-x-2"
              to="/cart"
              role="button"
              aria-label="Ver carrito"
            >
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4m0 0L7 13m0 0l-1.1 5H19M7 13l-1.1 5M7 13H5.4"/>
              </svg>
              <span>Carrito ({{ cartCount }})</span>
            </RouterLink>
          </div>
        </div>
      </div>
    </header>

    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Hero Section -->
      <div class="text-center mb-12">
        <div class="inline-flex items-center px-6 py-3 bg-orange-500/20 backdrop-blur-sm text-orange-300 rounded-full text-sm font-semibold mb-6 border border-orange-500/30">
          <svg class="w-5 h-5 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
          </svg>
          Catálogo Premium de Repuestos
        </div>
        <h1 class="text-5xl md:text-7xl font-black text-white mb-6">
          Productos
          <span class="bg-gradient-to-r from-orange-400 via-red-500 to-yellow-500 bg-clip-text text-transparent">
            Disponibles
          </span>
        </h1>
        <p class="text-2xl text-gray-300 max-w-3xl mx-auto leading-relaxed">
          Descubre la mejor selección de repuestos y accesorios para tu motocicleta
        </p>
      </div>

      <!-- Search and Filters -->
      <div class="bg-white/5 backdrop-blur-xl rounded-3xl shadow-2xl border border-white/10 p-8 mb-12">
        <div class="flex flex-col lg:flex-row gap-8">
          <!-- Search Bar -->
          <div class="flex-1">
            <div class="relative">
              <svg class="absolute left-4 top-1/2 transform -translate-y-1/2 w-6 h-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
              </svg>
              <input
                v-model="filters.search"
                type="search"
                placeholder="Buscar productos por nombre, marca, modelo..."
                class="w-full pl-14 pr-6 py-4 bg-white/10 backdrop-blur-sm border border-white/20 rounded-2xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-all duration-300"
                @input="debouncedSearch"
              />
            </div>
          </div>

          <!-- Filters -->
          <div class="flex flex-wrap gap-6">
            <div class="relative">
              <select
                v-model="filters.category_id"
                @change="fetchProducts"
                class="appearance-none bg-white/10 backdrop-blur-sm border border-white/20 rounded-2xl px-6 py-4 pr-12 text-white focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-all duration-300"
              >
                <option value="" class="bg-gray-800">Todas las categorías</option>
                <option v-for="category in categories" :key="category.id" :value="category.id" class="bg-gray-800">
                  {{ category.name }}
                </option>
              </select>
              <svg class="absolute right-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
              </svg>
            </div>

            <div class="relative">
              <select
                v-model="filters.store_id"
                @change="fetchProducts"
                class="appearance-none bg-white/10 backdrop-blur-sm border border-white/20 rounded-2xl px-6 py-4 pr-12 text-white focus:outline-none focus:ring-2 focus:ring-orange-500 focus:border-transparent transition-all duration-300"
              >
                <option value="" class="bg-gray-800">Todas las tiendas</option>
                <option v-for="store in stores" :key="store.id" :value="store.id" class="bg-gray-800">
                  {{ store.name }}
                </option>
              </select>
              <svg class="absolute right-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400 pointer-events-none" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
              </svg>
            </div>

            <label class="flex items-center space-x-4 bg-white/10 backdrop-blur-sm px-6 py-4 rounded-2xl cursor-pointer hover:bg-white/15 transition-all duration-300 border border-white/20">
              <input
                type="checkbox"
                v-model="filters.featured"
                @change="fetchProducts"
                class="w-5 h-5 bg-white/10 border-white/20 rounded focus:ring-orange-500 focus:ring-2"
              />
              <span class="text-white font-medium">Solo destacados</span>
            </label>
          </div>
        </div>
      </div>

      <!-- Products Grid -->
      <div v-if="loading" class="flex justify-center items-center py-20">
        <div class="animate-spin rounded-full h-16 w-16 border-b-4 border-orange-500"></div>
      </div>

      <div v-else-if="products.data.length === 0" class="text-center py-20">
        <div class="relative mb-12">
          <div class="w-40 h-40 bg-gradient-to-br from-gray-700 to-gray-800 rounded-full flex items-center justify-center mx-auto mb-8 shadow-2xl">
            <svg class="w-20 h-20 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-5.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"/>
            </svg>
          </div>
          <!-- Floating elements -->
          <div class="absolute top-10 left-1/4 w-8 h-8 bg-orange-500/20 rounded-full blur-sm animate-pulse"></div>
          <div class="absolute bottom-10 right-1/4 w-6 h-6 bg-blue-500/20 rounded-full blur-sm animate-pulse delay-1000"></div>
        </div>
        <h3 class="text-4xl font-black text-white mb-6">No hay productos que coincidan</h3>
        <p class="text-xl text-gray-400 mb-10 max-w-lg mx-auto leading-relaxed">Intenta con otros filtros o términos de búsqueda.</p>
        <button
          class="bg-gradient-to-r from-orange-500 to-red-600 text-white px-10 py-5 rounded-2xl font-bold hover:shadow-2xl hover:shadow-orange-500/25 transition-all duration-500 transform hover:scale-110 text-xl"
          @click="clearFilters"
        >
          <svg class="w-6 h-6 mr-3 inline" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/>
          </svg>
          Limpiar filtros
        </button>
      </div>

      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 mb-16">
        <article
          v-for="product in products.data"
          :key="product.id"
          class="group bg-white/5 backdrop-blur-xl rounded-3xl shadow-xl border border-white/10 overflow-hidden hover:shadow-2xl hover:shadow-orange-500/10 transition-all duration-500 transform hover:-translate-y-2"
          role="listitem"
        >
          <!-- Product Image -->
          <div class="relative aspect-square overflow-hidden bg-gradient-to-br from-gray-700 to-gray-800">
            <img
              :src="product.image_url || '/images/placeholders/product.png'"
              :alt="product.name"
              class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
              @error="onImgError($event)"
            />
            <div v-if="product.featured" class="absolute top-4 left-4 bg-gradient-to-r from-orange-500 to-red-600 text-white px-4 py-2 rounded-2xl text-sm font-bold shadow-lg">
              <svg class="w-4 h-4 inline mr-2" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
              </svg>
              Destacado
            </div>
            <div v-if="product.stock <= 5 && product.stock > 0" class="absolute top-4 right-4 bg-yellow-500 text-white px-4 py-2 rounded-2xl text-sm font-bold shadow-lg">
              <svg class="w-4 h-4 inline mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z"/>
              </svg>
              ¡Últimas!
            </div>
            <div v-if="product.stock <= 0" class="absolute inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center">
              <span class="bg-red-600 text-white px-6 py-3 rounded-2xl font-bold text-lg shadow-lg">Agotado</span>
            </div>

            <!-- Hover overlay -->
            <div class="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          </div>

          <!-- Product Info -->
          <div class="p-8">
            <div class="flex items-center justify-between mb-4">
              <span class="inline-flex items-center px-4 py-2 rounded-2xl text-sm font-semibold bg-orange-500/20 text-orange-300 border border-orange-500/30">
                {{ product.category?.name || 'Sin categoría' }}
              </span>
              <span class="text-sm text-gray-400 bg-white/10 px-3 py-1 rounded-full">{{ product.store?.name || 'Tienda' }}</span>
            </div>

            <h3 class="text-xl font-bold text-white mb-3 line-clamp-2 group-hover:text-orange-400 transition-colors duration-300">
              {{ product.name }}
            </h3>

            <p v-if="product.description" class="text-gray-400 text-sm mb-6 line-clamp-2">
              {{ product.description }}
            </p>

            <div class="flex items-center justify-between mb-6">
              <span class="text-3xl font-black text-white">{{ price(product.price) }}</span>
              <span
                class="text-sm font-semibold px-3 py-1 rounded-full"
                :class="{
                  'text-green-400 bg-green-500/20 border border-green-500/30': product.stock > 10,
                  'text-yellow-400 bg-yellow-500/20 border border-yellow-500/30': product.stock <= 10 && product.stock > 0,
                  'text-red-400 bg-red-500/20 border border-red-500/30': product.stock <= 0
                }"
              >
                {{ product.stock > 0 ? `${product.stock} en stock` : 'Agotado' }}
              </span>
            </div>

            <div class="flex gap-4">
              <button
                class="flex-1 bg-gradient-to-r from-orange-500 to-red-600 hover:from-orange-600 hover:to-red-700 text-white py-4 px-6 rounded-2xl font-bold hover:shadow-2xl hover:shadow-orange-500/25 transition-all duration-500 transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none flex items-center justify-center"
                @click="addToCart(product)"
                :disabled="product.stock <= 0"
              >
                <svg class="w-5 h-5 mr-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4m0 0L7 13m0 0l-1.1 5H19M7 13l-1.1 5M7 13H5.4"/>
                </svg>
                <span>{{ product.stock > 0 ? 'Agregar al carrito' : 'Agotado' }}</span>
              </button>
              <RouterLink
                class="bg-white/10 backdrop-blur-sm text-white py-4 px-6 rounded-2xl font-semibold hover:bg-white/20 transition-all duration-300 border border-white/20 flex items-center justify-center"
                :to="`/products/${product.id}`"
              >
                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
                </svg>
              </RouterLink>
            </div>
          </div>
        </article>
      </div>

      <!-- Pagination -->
      <div v-if="products.last_page > 1" class="flex justify-center items-center space-x-3">
        <button
          v-for="page in products.last_page"
          :key="page"
          class="px-6 py-3 rounded-2xl font-bold transition-all duration-300"
          :class="{
            'bg-gradient-to-r from-orange-500 to-red-600 text-white shadow-2xl shadow-orange-500/25': page === products.current_page,
            'bg-white/10 backdrop-blur-sm text-white border border-white/20 hover:bg-white/20': page !== products.current_page
          }"
          @click="goToPage(page)"
        >
          {{ page }}
        </button>
      </div>
    </main>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'

const router = useRouter()
const API = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'

const products = ref({ data: [], current_page: 1, last_page: 1 })
const categories = ref([])
const stores = ref([])
const loading = ref(true)
const cartCount = ref(0)

const filters = reactive({
  search: '',
  category_id: '',
  store_id: '',
  featured: false,
  page: 1
})

const fetchProducts = async () => {
  loading.value = true
  try {
    const params = { ...filters }
    if (!params.search) delete params.search
    if (!params.category_id) delete params.category_id
    if (!params.store_id) delete params.store_id
    if (!params.featured) delete params.featured

    const { data } = await axios.get(`${API}/api/products`, { params })
    products.value = data
  } catch (e) {
    console.error('Error cargando productos', e)
    products.value = { data: [], current_page: 1, last_page: 1 }
  } finally {
    loading.value = false
  }
}

const fetchCategories = async () => {
  try {
    const { data } = await axios.get(`${API}/api/categories`)
    categories.value = data.data || data
  } catch (e) {
    console.error('Error cargando categorías', e)
  }
}

const fetchStores = async () => {
  try {
    const { data } = await axios.get(`${API}/api/stores`)
    stores.value = data.data || data
  } catch (e) {
    console.error('Error cargando tiendas', e)
  }
}

const fetchCartCount = async () => {
  try {
    const { data } = await axios.get(`${API}/api/cart/count`)
    cartCount.value = data.count || 0
  } catch (e) {
    console.error('Error cargando contador del carrito', e)
  }
}

let timer
const debouncedSearch = () => {
  clearTimeout(timer)
  timer = setTimeout(() => {
    filters.page = 1
    fetchProducts()
  }, 250)
}

const goToPage = (page) => {
  filters.page = page
  fetchProducts()
}

const clearFilters = () => {
  filters.search = ''
  filters.category_id = ''
  filters.store_id = ''
  filters.featured = false
  filters.page = 1
  fetchProducts()
}

const price = (val) => {
  if (val == null) return '—'
  try {
    return new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(val)
  } catch {
    return `$${val}`
  }
}

const addToCart = async (product) => {
  try {
    await axios.post(`${API}/api/cart`, {
      product_id: product.id,
      quantity: 1
    })
    fetchCartCount()
    // Mostrar notificación de éxito
  } catch (e) {
    console.error('Error agregando al carrito', e)
  }
}

const onImgError = (e) => {
  e.target.src = '/images/placeholders/product.png'
}

onMounted(() => {
  fetchProducts()
  fetchCategories()
  fetchStores()
  fetchCartCount()
})
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.delay-1000 {
  animation-delay: 1s;
}
</style>

// comercio-plus-frontend-react/app/products/page.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import API from '@/lib/api'
import type { Category as CategoryType, Product } from '@/types/api'

export default function Products() {
  const [searchParams] = useSearchParams()
  const [products, setProducts] = useState<Product[]>([])
  const [categories, setCategories] = useState<CategoryType[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedCategory, setSelectedCategory] = useState('')
  const [sortBy, setSortBy] = useState('recent')
  const [pagination, setPagination] = useState({
    current_page: 1,
    last_page: 1,
    per_page: 12,
    total: 0,
  })

  const searchTimeout = useRef<number | null>(null)

  const visiblePages = useMemo(() => {
    const current = pagination.current_page
    const last = pagination.last_page
    const delta = 2
    const range: number[] = []
    const rangeWithDots: Array<number | string> = []

    for (let i = Math.max(2, current - delta); i <= Math.min(last - 1, current + delta); i += 1) {
      range.push(i)
    }

    if (current - delta > 2) {
      rangeWithDots.push(1, '...')
    } else {
      rangeWithDots.push(1)
    }

    rangeWithDots.push(...range)

    if (current + delta < last - 1) {
      rangeWithDots.push('...', last)
    } else if (last > 1) {
      rangeWithDots.push(last)
    }

    return rangeWithDots.filter(
      (item, index, self) => item !== '...' || self.indexOf(item) === self.lastIndexOf(item),
    )
  }, [pagination.current_page, pagination.last_page])

  const fetchProducts = async (page = 1) => {
    try {
      setLoading(true)
      setError('')

      const params: Record<string, string | number | undefined> = {
        page,
        per_page: 12,
        search: searchQuery,
        category: selectedCategory || undefined,
        sort: sortBy === 'recent' ? undefined : sortBy,
      }

      const response = await API.get('/products', { params })
      setProducts(response.data.data || [])
      setPagination({
        current_page: response.data.current_page || 1,
        last_page: response.data.last_page || 1,
        per_page: response.data.per_page || 12,
        total: response.data.total || 0,
      })
    } catch (err: any) {
      console.error('Error fetching products:', err)
      setError(err.response?.data?.message || 'Error al cargar los productos. Inténtalo de nuevo.')
    } finally {
      setLoading(false)
    }
  }

  const fetchCategories = async () => {
    try {
      const response = await API.get('/categories')
      setCategories(response.data || [])
    } catch (err) {
      console.error('Error fetching categories:', err)
    }
  }

  useEffect(() => {
    const initialCategory = searchParams.get('category') || searchParams.get('category_id') || ''
    if (initialCategory) {
      setSelectedCategory(initialCategory)
    }
    fetchCategories()
    fetchProducts()
    return () => {
      if (searchTimeout.current) {
        window.clearTimeout(searchTimeout.current)
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  useEffect(() => {
    if (searchTimeout.current) {
      window.clearTimeout(searchTimeout.current)
    }
    searchTimeout.current = window.setTimeout(() => fetchProducts(1), 450)
    return () => {
      if (searchTimeout.current) {
        window.clearTimeout(searchTimeout.current)
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchQuery, selectedCategory, sortBy])

  const goToPage = (page: number) => {
    if (page >= 1 && page <= pagination.last_page) {
      fetchProducts(page)
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900">
      <div className="bg-white shadow">
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-gray-900">Productos</h1>
          <p className="mt-2 text-sm text-gray-600">Descubre los mejores repuestos para moto</p>
        </div>
      </div>

      <div className="bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-1">
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <svg className="h-5 w-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                  </svg>
                </div>
                <input
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  type="text"
                  placeholder="Buscar productos..."
                  className="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white text-gray-900 placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-orange-500 focus:border-orange-500"
                />
              </div>
            </div>

            <div className="w-full md:w-48">
              <select
                value={selectedCategory}
                onChange={(e) => setSelectedCategory(e.target.value)}
                className="select-light block w-full py-2 px-3 border border-gray-300 bg-white text-gray-900 rounded-md shadow-sm focus:outline-none focus:ring-orange-500 focus:border-orange-500"
              >
                <option value="">Todas las categorías</option>
                {categories.map((category) => (
                  <option key={category.id} value={category.id}>
                    {category.name}
                  </option>
                ))}
              </select>
            </div>

            <div className="w-full md:w-48">
              <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="select-light block w-full py-2 px-3 border border-gray-300 bg-white text-gray-900 rounded-md shadow-sm focus:outline-none focus:ring-orange-500 focus:border-orange-500"
              >
                <option value="recent">Más recientes</option>
                <option value="price_asc">Precio: menor a mayor</option>
                <option value="price_desc">Precio: mayor a menor</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      {loading && (
        <div className="flex justify-center items-center py-12">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-orange-600"></div>
        </div>
      )}

      {!loading && error && (
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <div className="bg-red-50 border border-red-200 rounded-md p-4">
            <div className="flex">
              <div className="flex-shrink-0">
                <svg className="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                </svg>
              </div>
              <div className="ml-3">
                <h3 className="text-sm font-medium text-red-800">Error al cargar productos</h3>
                <div className="mt-2 text-sm text-red-700">{error}</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {!loading && !error && (
        <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
          <div className="mb-6">
            <p className="text-sm text-gray-700">
              Mostrando {products.length} de {pagination.total} productos
            </p>
          </div>

          {products.length === 0 ? (
            <div className="text-center py-12">
              <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
              </svg>
              <h3 className="mt-2 text-sm font-medium text-gray-900">No se encontraron productos</h3>
              <p className="mt-1 text-sm text-gray-500">Intenta cambiar los filtros de búsqueda.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {products.map((product) => (
                <div key={product.id} className="bg-white overflow-hidden shadow rounded-lg hover:shadow-lg transition-shadow duration-300">
                  <div className="aspect-w-1 aspect-h-1 bg-gray-200">
                    <img
                      src={product.image_url || '/placeholder-product.png'}
                      alt={product.name}
                      className="w-full h-48 object-center object-cover"
                    />
                  </div>

                  <div className="p-4">
                    <div className="flex items-center justify-between">
                      <h3 className="text-sm font-medium text-gray-900 truncate">{product.name}</h3>
                      <p className="text-sm font-medium text-gray-900">${product.price}</p>
                    </div>

                    <p className="mt-1 text-sm text-gray-500 line-clamp-2">{product.description}</p>

                    <div className="mt-2">
                      {product.category && (
                        <p className="text-xs text-gray-600 bg-gray-100 px-2 py-1 rounded-full inline-block">
                          {product.category.name}
                        </p>
                      )}
                    </div>

                    <div className="mt-4 flex items-center justify-between">
                      <div className="flex items-center">
                        <div className="flex items-center">
                          {Array.from({ length: 5 }).map((_, i) => (
                            <svg
                              key={i}
                              className={`w-3 h-3 ${i + 1 <= Math.floor(product.rating || 0) ? 'text-yellow-400' : 'text-gray-300'}`}
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                            </svg>
                          ))}
                        </div>
                        <span className="ml-1 text-xs text-gray-600">{product.rating || '0.0'}</span>
                      </div>
                    </div>

                    <div className="mt-4 flex gap-2">
                      <Link
                        to={`/product/${product.id}`}
                        className="flex-1 bg-gray-100 text-gray-700 px-3 py-2 rounded-md text-sm font-medium text-center hover:bg-gray-200 transition-colors"
                      >
                        Ver detalles
                      </Link>
                      <button
                        onClick={() => alert(`Producto "${product.name}" agregado al carrito (funcionalidad pendiente)`)}
                        className="flex-1 bg-orange-600 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-orange-700 transition-colors"
                      >
                        Agregar
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {pagination.last_page > 1 && (
            <div className="mt-8 flex justify-center">
              <nav className="relative z-0 inline-flex rounded-md shadow-sm -space-x-px">
                <button
                  onClick={() => goToPage(pagination.current_page - 1)}
                  disabled={pagination.current_page === 1}
                  className="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" />
                  </svg>
                </button>

                {visiblePages.map((page) => (
                  <button
                    key={String(page)}
                    onClick={() => (typeof page === 'number' ? goToPage(page) : null)}
                    className={`relative inline-flex items-center px-4 py-2 border text-sm font-medium ${
                      page === pagination.current_page
                        ? 'z-10 bg-orange-50 border-orange-500 text-orange-600'
                        : 'bg-white border-gray-300 text-gray-500 hover:bg-gray-50'
                    } ${typeof page === 'string' ? 'cursor-default' : 'cursor-pointer'}`}
                  >
                    {page}
                  </button>
                ))}

                <button
                  onClick={() => goToPage(pagination.current_page + 1)}
                  disabled={pagination.current_page === pagination.last_page}
                  className="relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7" />
                  </svg>
                </button>
              </nav>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
