// comercio-plus-frontend/src/components/products/ProductCard.tsx
﻿import { Link } from 'react-router-dom'
import Badge from '@/components/ui/Badge'
import { buttonVariants } from '@/components/ui/button'
import { formatPrice, resolveMediaUrl } from '@/lib/format'
import type { Product } from '@/types/api'

type Props = {
  product: Product
  onAdd: (product: Product) => void
  onImageClick: (product: Product) => void
}

export default function ProductCard({ product, onAdd, onImageClick }: Props) {
  const image = resolveMediaUrl(product.image_url || product.image)

  const ratingValue = Number(product.rating ?? product.average_rating)
  const hasRating = Number.isFinite(ratingValue) && ratingValue > 0

  const reviewsCount = Number(product.reviews_count ?? 0)
  const hasReviews = Number.isFinite(reviewsCount) && reviewsCount > 0

  return (
    <article className="group h-full overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-soft transition-all duration-200 hover:-translate-y-0.5 hover:border-slate-300 dark:border-white/10 dark:bg-white/5 dark:hover:border-white/20">
      <div className="flex h-full flex-col">
        <button
          type="button"
          onClick={() => onImageClick(product)}
          className="relative text-left"
          aria-label={`Ver imagen grande y detalles de ${product.name}`}
        >
          <div className="relative aspect-square overflow-hidden bg-white">
            {image ? (
              <img
                src={image}
                alt={product.name}
                className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.04]"
              />
            ) : (
              <div className="flex h-full w-full items-center justify-center px-4 text-center text-[13px] font-medium text-slate-500 dark:text-white/60">
                Sin imagen
              </div>
            )}

            <div className="absolute left-3 top-3 flex flex-wrap gap-2">
              {product.category?.name && <Badge variant="neutral">{product.category.name}</Badge>}
              {typeof product.stock === 'number' && product.stock <= 3 && product.stock > 0 && (
                <Badge variant="brand">Ultimas</Badge>
              )}
              {typeof product.stock === 'number' && product.stock === 0 && (
                <Badge variant="danger">Agotado</Badge>
              )}
            </div>
          </div>
        </button>

        <div className="flex flex-1 flex-col gap-2 px-4 pt-3 pb-4">
          <div className="flex items-end justify-between gap-3">
            <p className="text-[20px] font-extrabold leading-[1] text-slate-900 dark:text-white sm:text-[22px]">
              ${formatPrice(product.price)}
            </p>

            {hasRating && (
              <div className="flex items-center gap-1 text-[12px] text-slate-500 dark:text-white/60">
                <span className="inline-flex items-center gap-1 rounded-full bg-white/80 px-2.5 py-1 text-[12px] text-slate-900 backdrop-blur dark:bg-white/10 dark:text-white">
                  <span aria-hidden>*</span>
                  <span className="font-semibold">{ratingValue.toFixed(1)}</span>
                  {hasReviews ? <span className="opacity-80">({reviewsCount})</span> : null}
                </span>
              </div>
            )}
          </div>

          <h3 className="line-clamp-2 min-h-[34px] text-[13px] font-semibold leading-[1.25] text-slate-800 dark:text-white sm:min-h-[38px] sm:text-[14px]">
            {product.name}
          </h3>

          <p className="text-[12px] text-slate-500 dark:text-white/60">Stock: {product.stock}</p>

          <div className="mt-auto grid grid-cols-2 gap-2 pt-2">
            <Link to={`/product/${product.id}`} className={buttonVariants('secondary', 'h-10 justify-center text-[13px]')}>
              Ver
            </Link>

            <button
              type="button"
              onClick={() => onAdd(product)}
              className={buttonVariants('primary', 'h-10 justify-center text-[13px] disabled:cursor-not-allowed disabled:opacity-50')}
              disabled={typeof product.stock === 'number' && product.stock === 0}
            >
              Agregar
            </button>
          </div>
        </div>
      </div>
    </article>
  )
}

// resources/js/components/ProductCard.vue
<template>
  <article class="group rounded-2xl border border-border/60 bg-white dark:bg-neutral-900 shadow-sm hover:shadow-md transition p-3">
    <div class="relative aspect-[4/3] rounded-xl overflow-hidden bg-neutral-100 dark:bg-neutral-800">
      <img v-if="image" :src="image" :alt="name" class="w-full h-full object-cover" />
      <div v-else class="w-full h-full grid place-items-center text-neutral-500">Sin imagen</div>

      <div class="absolute top-3 left-3 flex gap-2">
        <span v-if="outOfStock" class="px-2 py-0.5 text-xs rounded-full bg-neutral-900/80 text-white">Sin stock</span>
        <span v-if="discount" class="px-2 py-0.5 text-xs rounded-full bg-primary text-white">-{{ discount }}%</span>
      </div>

      <label class="absolute top-3 right-3 inline-flex items-center gap-2">
        <input type="checkbox" class="size-4 accent-primary rounded">
      </label>
    </div>

    <div class="mt-3 space-y-1">
      <h3 class="font-medium text-neutral-900 dark:text-neutral-100 line-clamp-2">{{ name }}</h3>
      <div class="text-sm text-neutral-600 dark:text-neutral-400 flex items-center gap-2">
        <span class="font-semibold text-neutral-900 dark:text-neutral-100">{{ formattedPrice }}</span>
        <span>·</span>
        <span>★ {{ formattedRating }}</span>
        <span>·</span>
        <span>{{ stock }} u</span>
      </div>
      <div class="flex items-center gap-2 pt-2">
        <button class="px-3 py-1.5 rounded-lg bg-primary text-white hover:opacity-90">Editar</button>
        <button class="px-3 py-1.5 rounded-lg border border-border/70 hover:bg-neutral-50 dark:hover:bg-neutral-800">Ver</button>
        <button class="ml-auto px-2 py-1 rounded-lg hover:bg-neutral-50 dark:hover:bg-neutral-800">⋮</button>
      </div>
    </div>
  </article>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  name: String,
  price: Number,
  stock: Number,
  image: String,
  rating: Number,
  discount: Number,
  outOfStock: Boolean,
})

const formattedPrice = computed(() =>
  props.price != null ? `$${props.price.toLocaleString('es-CO')}` : '—'
)
const formattedRating = computed(() =>
  typeof props.rating === 'number' ? props.rating.toFixed(1) : '—'
)
</script>
