// comercio-plus-frontend/src/pages/Cart.tsx
import { Link } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { Icon } from '@/components/Icon'
import { useCart } from '@/context/CartContext'

export default function Cart() {
  const { items, removeFromCart, updateQuantity, totalItems, totalPrice } = useCart()

  if (items.length === 0) {
    return (
      <div className="min-h-screen bg-slate-50 py-12">
        <div className="mx-auto max-w-7xl px-6">
          <div className="rounded-2xl bg-white p-12 text-center shadow-premium">
            <div className="mb-6 inline-flex h-24 w-24 items-center justify-center rounded-full bg-slate-100">
              <Icon name="cart" size={48} className="text-slate-400" />
            </div>
            <h2 className="mb-4 text-3xl font-bold text-slate-900">Tu carrito está vacío</h2>
            <p className="mb-8 text-lg text-slate-600">
              Agrega productos para empezar a comprar
            </p>
            <Link
              to="/products"
              className="inline-flex items-center gap-2 rounded-xl bg-comercioplus-600 px-8 py-4 font-semibold text-white transition-all hover:bg-comercioplus-700"
            >
              <Icon name="search" size={20} />
              Explorar productos
            </Link>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-slate-50 py-12">
      <div className="mx-auto max-w-7xl px-6">
        <div className="mb-4 flex flex-wrap items-center gap-2 text-sm">
          <Link to="/stores" className="font-medium text-slate-600 transition hover:text-slate-900">
            Tiendas
          </Link>
          <span className="text-slate-400">/</span>
          <span className="font-semibold text-slate-900">Carrito</span>
        </div>
        {/* Header */}
        <div className="mb-8">
          <h1 className="mb-2 text-4xl font-bold text-slate-900">Carrito de compras</h1>
          <p className="text-lg text-slate-600">{totalItems} productos</p>
        </div>

        <div className="grid gap-8 lg:grid-cols-3">
          {/* Items del carrito */}
          <div className="lg:col-span-2">
            <div className="space-y-4">
              <AnimatePresence>
                {items.map((item) => (
                  <motion.div
                    key={item.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, x: -100 }}
                    className="rounded-2xl border-2 border-slate-200 bg-white p-6 transition-all hover:border-comercioplus-500"
                  >
                    <div className="flex gap-6">
                      {/* Imagen */}
                      <div className="h-24 w-24 flex-shrink-0 overflow-hidden rounded-xl bg-slate-100">
                        <img
                          src={item.image}
                          alt={item.name}
                          className="h-full w-full object-cover"
                        />
                      </div>

                      {/* Info */}
                      <div className="flex-1">
                        <div className="mb-2 flex items-start justify-between">
                          <div>
                            <h3 className="mb-1 text-lg font-bold text-slate-900">
                              {item.name}
                            </h3>
                            <p className="text-sm text-slate-500">
                              Vendido por: {item.seller}
                            </p>
                          </div>
                          <button
                            onClick={() => removeFromCart(item.productId)}
                            className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition-colors hover:bg-danger/10 hover:text-danger"
                          >
                            <Icon name="trash" size={18} />
                          </button>
                        </div>

                        <div className="flex items-center justify-between">
                          {/* Precio */}
                          <div>
                            <span className="text-2xl font-bold text-comercioplus-600">
                              ${(item.price * item.quantity).toLocaleString('es-CO')}
                            </span>
                            <span className="ml-2 text-sm text-slate-500">
                              ${item.price.toLocaleString('es-CO')} c/u
                            </span>
                          </div>

                          {/* Cantidad */}
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => updateQuantity(item.productId, item.quantity - 1)}
                              className="flex h-8 w-8 items-center justify-center rounded-lg border-2 border-slate-200 text-slate-600 transition-all hover:border-comercioplus-500 hover:bg-comercioplus-50 hover:text-comercioplus-600"
                            >
                              <Icon name="minus" size={16} />
                            </button>
                            <span className="w-12 text-center font-semibold text-slate-900">
                              {item.quantity}
                            </span>
                            <button
                              onClick={() => updateQuantity(item.productId, item.quantity + 1)}
                              className="flex h-8 w-8 items-center justify-center rounded-lg border-2 border-slate-200 text-slate-600 transition-all hover:border-comercioplus-500 hover:bg-comercioplus-50 hover:text-comercioplus-600"
                            >
                              <Icon name="plus" size={16} />
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </div>

          {/* Resumen */}
          <div className="lg:col-span-1">
            <div className="sticky top-24 rounded-2xl border-2 border-slate-200 bg-white p-6">
              <h2 className="mb-6 text-2xl font-bold text-slate-900">Resumen del pedido</h2>

              <div className="mb-6 space-y-4">
                <div className="flex justify-between text-slate-600">
                  <span>Subtotal</span>
                  <span className="font-semibold">
                    ${totalPrice.toLocaleString('es-CO')}
                  </span>
                </div>
                <div className="flex justify-between text-slate-600">
                  <span>Envío</span>
                  <span className="font-semibold text-green-600">Gratis</span>
                </div>
                <div className="border-t-2 border-slate-100 pt-4">
                  <div className="flex justify-between">
                    <span className="text-lg font-semibold text-slate-900">Total</span>
                    <span className="text-2xl font-bold text-comercioplus-600">
                      ${totalPrice.toLocaleString('es-CO')} COP
                    </span>
                  </div>
                </div>
              </div>

              {/* Botón checkout */}
              <Link
                to="/checkout"
                className="mb-4 flex w-full items-center justify-center gap-2 rounded-xl bg-comercioplus-600 py-4 font-bold text-white transition-all hover:bg-comercioplus-700 hover:shadow-lg hover:shadow-comercioplus-600/25"
              >
                <Icon name="lock" size={20} />
                Proceder al pago
              </Link>

              <Link
                to="/products"
                className="flex w-full items-center justify-center gap-2 rounded-xl border-2 border-slate-200 bg-white py-4 font-semibold text-slate-700 transition-all hover:bg-slate-50"
              >
                <Icon name="arrow-left" size={20} />
                Seguir comprando
              </Link>

              {/* Trust badges */}
              <div className="mt-6 space-y-3 rounded-xl bg-slate-50 p-4">
                <div className="flex items-center gap-3">
                  <Icon name="shield" size={20} className="text-green-600" />
                  <span className="text-sm text-slate-700">Compra 100% segura</span>
                </div>
                <div className="flex items-center gap-3">
                  <Icon name="truck" size={20} className="text-blue-600" />
                  <span className="text-sm text-slate-700">Envío rápido</span>
                </div>
                <div className="flex items-center gap-3">
                  <Icon name="refresh" size={20} className="text-comercioplus-600" />
                  <span className="text-sm text-slate-700">Devoluciones fáciles</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// resources/js/Pages/Cart/Index.vue
<!-- resources/js/Pages/Cart/Index.vue -->
<script setup>
import { ref, computed, onMounted } from 'vue'
import { Link, usePage } from '@inertiajs/vue3'
import axios from 'axios'

// Componentes UI
import Header from '@/components/Header.vue'
import Footer from '@/components/Footer.vue'

const API = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'

const cartItems = ref([])
const loading = ref(true)

// --- Data Fetching ---
const fetchCart = async () => {
  loading.value = true
  try {
    // Usar el endpoint de la API para obtener el carrito
    const response = await axios.get(`${API}/api/cart`)
    cartItems.value = response.data.data || response.data 
  } catch (e) {
    console.error('Error cargando el carrito:', e)
    cartItems.value = []
  } finally {
    loading.value = false
  }
}

// --- Cart Actions ---
const updateQuantity = async (item, newQuantity) => {
  if (newQuantity < 1 || newQuantity > item.product.stock) return
  try {
    await axios.put(`${API}/api/cart/${item.id}`, { quantity: newQuantity })
    item.quantity = newQuantity
  } catch (e) {
    console.error('Error actualizando la cantidad:', e)
  }
}

const removeItem = async (item) => {
  if (!confirm(`¿Estás seguro de que quieres eliminar "${item.product.name}" del carrito?`)) return
  try {
    await axios.delete(`${API}/api/cart/${item.id}`)
    cartItems.value = cartItems.value.filter(i => i.id !== item.id)
  } catch (e) {
    console.error('Error eliminando el producto:', e)
  }
}

// --- Computed Properties ---
const subtotal = computed(() => cartItems.value.reduce((sum, item) => sum + (item.product.price * item.quantity), 0))
const totalItems = computed(() => cartItems.value.reduce((sum, item) => sum + item.quantity, 0))
const shipping = computed(() => subtotal.value >= 100000 ? 0 : 15000) // Envío gratis sobre $100.000
const total = computed(() => subtotal.value + shipping.value)

// --- Helpers ---
const price = (val) => {
  if (val == null) return '—'
  return new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(val)
}

const onImgError = (e) => {
  e.target.src = '/images/product_placeholder.jpg'
}

// --- Lifecycle ---
onMounted(() => {
  fetchCart()
})

</script>

<template>
  <div class="min-h-screen bg-cp-bg text-cp-text">
    <Header />

    <main class="container mx-auto px-6 py-12">
      <!-- Titulo -->
      <div class="mb-10">
        <h1 class="text-4xl font-semibold text-cp-text">Tu Carrito de Compras</h1>
        <p v-if="!loading" class="text-cp-sub mt-2">
          Tienes {{ totalItems }} {{ totalItems === 1 ? 'producto' : 'productos' }} en tu carrito.
        </p>
      </div>

      <!-- Loading State -->
      <div v-if="loading" class="text-center py-20">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-comercioplus mx-auto"></div>
        <p class="mt-4 text-cp-sub">Cargando tu carrito...</p>
      </div>

      <!-- Empty Cart State -->
      <div v-else-if="cartItems.length === 0" class="text-center bg-cp-surface rounded-xl-20 shadow-cp-card p-12">
        <img src="/assets/icons/ic_cart.svg" class="h-16 w-16 mx-auto text-cp-sub opacity-50" alt="Carrito vacío"/>
        <h2 class="text-2xl font-semibold text-cp-text mt-6">Tu carrito está vacío</h2>
        <p class="text-cp-sub mt-2 mb-8">Parece que aún no has añadido productos. ¡Explora nuestras tiendas!</p>
        <Link
          href="/products"
          class="inline-block bg-comercioplus text-white px-8 py-3 rounded-lg-16 font-medium hover:bg-comercioplus-600 transition-transform transform hover:scale-105"
        >
          Explorar Productos
        </Link>
      </div>

      <!-- Cart Content -->
      <div v-else class="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
        <!-- Cart Items -->
        <div class="lg:col-span-2 bg-cp-surface rounded-xl-20 shadow-cp-card overflow-hidden">
            <div class="divide-y divide-gray-200">
              <div
                v-for="item in cartItems"
                :key="item.id"
                class="p-6 hover:bg-gray-50/50 transition-colors duration-300"
              >
                <div class="flex items-center space-x-6">
                  <!-- Imagen -->
                  <Link :href="`/products/${item.product.id}`" class="flex-shrink-0">
                    <img
                      :src="item.product.image_url || '/images/product_placeholder.jpg'"
                      :alt="item.product.name"
                      class="w-24 h-24 object-cover rounded-lg-16 border border-gray-200"
                      @error="onImgError"
                    />
                  </Link>

                  <!-- Detalles -->
                  <div class="flex-1 min-w-0">
                    <h3 class="text-lg font-semibold text-cp-text truncate">{{ item.product.name }}</h3>
                    <p class="text-sm text-cp-sub mt-1">Vendido por: {{ item.product.store?.name || 'Tienda' }}</p>
                    <p class="text-lg font-bold text-comercioplus mt-2">{{ price(item.product.price) }}</p>
                  </div>

                  <!-- Controles -->
                  <div class="flex flex-col items-center space-y-2">
                    <div class="flex items-center border border-gray-200 rounded-lg p-1">
                      <button @click="updateQuantity(item, item.quantity - 1)" :disabled="item.quantity <= 1" class="w-8 h-8 rounded-md hover:bg-gray-100 disabled:opacity-50">-</button>
                      <span class="w-10 text-center font-medium">{{ item.quantity }}</span>
                      <button @click="updateQuantity(item, item.quantity + 1)" :disabled="item.quantity >= item.product.stock" class="w-8 h-8 rounded-md hover:bg-gray-100 disabled:opacity-50">+</button>
                    </div>
                    <button @click="removeItem(item)" class="text-xs text-red-500 hover:text-red-700">Eliminar</button>
                  </div>

                  <!-- Total Item -->
                  <div class="text-right">
                    <p class="text-lg font-semibold text-cp-text">{{ price(item.product.price * item.quantity) }}</p>
                  </div>
                </div>
              </div>
            </div>
        </div>

        <!-- Resumen del Pedido -->
        <div class="lg:col-span-1">
          <div class="sticky top-24">
            <div class="bg-cp-surface rounded-xl-20 shadow-cp-card p-6">
              <h3 class="text-xl font-semibold mb-6">Resumen del pedido</h3>
              <div class="space-y-4 mb-6 text-cp-sub">
                <div class="flex justify-between"><span>Subtotal</span> <span class="font-medium text-cp-text">{{ price(subtotal) }}</span></div>
                <div class="flex justify-between"><span>Envío</span> <span class="font-medium text-cp-text">{{ shipping === 0 ? 'Gratis' : price(shipping) }}</span></div>
              </div>
              <div v-if="shipping === 0" class="text-sm text-green-700 bg-green-100 p-3 rounded-lg mb-6">
                  ¡Felicidades! Tu envío es gratis.
              </div>
              <div class="border-t border-gray-200 pt-6 mb-6">
                <div class="flex justify-between items-center">
                  <span class="text-lg font-semibold">Total</span>
                  <span class="text-2xl font-bold text-comercioplus">{{ price(total) }}</span>
                </div>
              </div>
              <Link
                href="/checkout"
                class="w-full block text-center bg-comercioplus text-white py-3 rounded-lg-16 font-semibold hover:bg-comercioplus-600 transition-all transform hover:scale-105"
              >
                Proceder al Pago
              </Link>
              <div class="mt-6 text-center text-xs text-cp-sub">
                <p>🔒 Pago seguro garantizado</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

    <Footer />
  </div>
</template>
