// comercio-plus-frontend/src/views/Register.vue
<template>
  <div class="space-y-6">
    <div class="space-y-1">
      <p class="text-sm text-muted">Crea tu cuenta para vender o comprar</p>
      <h1 class="text-3xl font-semibold text-white">Crear cuenta</h1>
    </div>

    <form class="space-y-5" @submit.prevent="handleSubmit">
      <div class="space-y-4">
        <div class="space-y-1">
          <label for="name" class="text-sm text-muted">Nombre</label>
          <input id="name" name="name" type="text" autocomplete="name" required class="input-dark"
            placeholder="Nombre completo" v-model="form.name" />
        </div>

        <div class="space-y-1">
          <label for="email" class="text-sm text-muted">Correo electrónico</label>
          <input id="email" name="email" type="email" autocomplete="email" required class="input-dark"
            placeholder="tu@correo.com" v-model="form.email" />
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="space-y-1">
            <label for="password" class="text-sm text-muted">Contraseña</label>
            <input
              id="password"
              name="password"
              type="password"
              autocomplete="new-password"
              required
            class="input-dark"
            placeholder="********"
            v-model="form.password"
          />
          </div>
          <div class="space-y-1">
            <label for="password_confirmation" class="text-sm text-muted">Confirmar contraseña</label>
            <input
              id="password_confirmation"
              name="password_confirmation"
              type="password"
              autocomplete="new-password"
              required
            class="input-dark"
            placeholder="Repite tu contraseña"
            v-model="form.password_confirmation"
          />
          </div>
        </div>
      </div>

      <div v-if="error" class="rounded-2xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-100">
        {{ error }}
      </div>

      <button type="submit" class="btn-primary w-full md:w-auto justify-center" :disabled="loading">
        <span v-if="loading" class="flex items-center gap-2">
          <svg class="animate-spin h-4 w-4 text-white" viewBox="0 0 24 24" fill="none">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
          </svg>
          Creando...
        </span>
        <span v-else>Crear cuenta</span>
      </button>

      <p class="text-center text-sm text-muted">
        ¿Ya tienes cuenta?
        <router-link to="/login" class="text-brand-200 hover:text-white font-medium">Inicia sesión</router-link>
      </p>
    </form>
  </div>
</template>

<script>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import API from '../services/api.js'

export default {
  name: 'Register',
  setup() {
    const router = useRouter()
    const loading = ref(false)
    const error = ref('')
    const form = reactive({
      name: '',
      email: '',
      password: '',
      password_confirmation: ''
    })

    const handleSubmit = async () => {
      loading.value = true
      error.value = ''

      try {
        const { data } = await API.post('/register', {
          name: form.name,
          email: form.email,
          password: form.password,
          password_confirmation: form.password_confirmation
        })

        if (data) {
          localStorage.setItem('user', JSON.stringify(data.user))
          if (data.token) {
            localStorage.setItem('token', data.token)
            API.defaults.headers.common.Authorization = `Bearer ${data.token}`
          }
          router.push('/dashboard')
        }
      } catch (err) {
        console.error('Register error:', err)
        error.value = err.response?.data?.message || 'Error al crear la cuenta. Verifica tus datos.'
      } finally {
        loading.value = false
      }
    }

    return {
      form,
      loading,
      error,
      handleSubmit
    }
  }
}
</script>

// comercio-plus-frontend/src/app/register/page.tsx
import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import API from '@/lib/api'
import Button from '@/components/ui/button'
import Input from '@/components/ui/Input'
import Select from '@/components/ui/Select'
import ThemeToggle from '@/components/theme/ThemeToggle'

export default function Register() {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [form, setForm] = useState({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
    role: 'merchant',
  })

  const resolvePostAuthRoute = async (role?: string) => {
    if (role === 'merchant') {
      try {
        await API.get('/my/store')
        return '/dashboard'
      } catch {
        return '/store/create'
      }
    }
    return '/stores'
  }

  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault()
    setLoading(true)
    setError('')

    try {
      const { data } = await API.post('/register', {
        name: form.name,
        email: form.email,
        password: form.password,
        password_confirmation: form.password_confirmation,
        role: form.role,
      })

      if (data) {
        localStorage.setItem('user', JSON.stringify(data.user))
        if (data.token) {
          localStorage.setItem('token', data.token)
          API.defaults.headers.common.Authorization = `Bearer ${data.token}`
        }
        const route = await resolvePostAuthRoute(data.user?.role)
        navigate(route)
      }
    } catch (err: any) {
      console.error('Register error:', err)
      const status = err?.response?.status
      const message = err?.response?.data?.message || 'Error al crear la cuenta. Verifica tus datos.'
      setError(status ? `${message} (HTTP ${status})` : message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="relative rounded-[28px] border border-white/25 bg-white/10 px-6 py-7 sm:px-8 sm:py-8 shadow-[0_30px_80px_rgba(0,0,0,0.35)] backdrop-blur-xl">
      {/* Toggle sol/luna */}
      <div className="absolute right-4 top-4">
        <ThemeToggle />
      </div>

      <div className="flex flex-col items-center text-center">
        <div className="relative flex h-16 w-16 items-center justify-center rounded-full border border-white/40">
          <div className="flex h-10 w-10 items-center justify-center rounded-full border border-white/60 text-slate-900 dark:text-white">
            <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M12 12c2.761 0 5-2.239 5-5s-2.239-5-5-5-5 2.239-5 5 2.239 5 5 5z" />
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M4 20c0-3.314 3.134-6 8-6s8 2.686 8 6" />
            </svg>
          </div>
        </div>

        <div className="mt-4 flex w-full items-center gap-4 text-slate-600 dark:text-white/70">
          <span className="h-px flex-1 bg-white/30" />
          <span className="text-[11px] uppercase tracking-[0.4em]">ComercioPlus</span>
          <span className="h-px flex-1 bg-white/30" />
        </div>
      </div>

      <div className="mt-6 text-center">
        <h1 className="text-2xl font-semibold text-slate-900 dark:text-white">Crear cuenta</h1>
        <p className="text-sm text-slate-600 dark:text-white/70">Crea tu cuenta para vender o comprar</p>

        <span className="mt-3 inline-flex items-center gap-2 rounded-full border border-white/40 px-3 py-1 text-xs font-medium text-slate-700 dark:text-white/80">
          Comerciante o cliente
        </span>
      </div>

      <form className="mt-6 space-y-4" onSubmit={handleSubmit}>
        <div className="space-y-4">
          <div className="flex items-center overflow-hidden rounded-xl border border-white/40 bg-white/90 text-slate-900 shadow-sm">
            <span className="flex h-11 w-11 items-center justify-center bg-panel text-white/80">
              <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M12 12c2.761 0 5-2.239 5-5s-2.239-5-5-5-5 2.239-5 5 2.239 5 5 5z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M4 20c0-3.314 3.134-6 8-6s8 2.686 8 6" />
              </svg>
            </span>
            <label htmlFor="name" className="sr-only">Nombre</label>
            <Input
              id="name"
              name="name"
              type="text"
              autoComplete="name"
              required
              placeholder="Nombre completo"
              className="!border-0 !bg-transparent !text-slate-900 !placeholder:text-slate-400 !py-2.5 !px-4 focus:!border-0 focus:!ring-0"
              value={form.name}
              onChange={(e) => setForm((prev) => ({ ...prev, name: e.target.value }))}
            />
          </div>

          <div className="flex items-center overflow-hidden rounded-xl border border-white/40 bg-white/90 text-slate-900 shadow-sm">
            <span className="flex h-11 w-11 items-center justify-center bg-panel text-white/80">
              <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M3 8l9 6 9-6M4 6h16a2 2 0 012 2v8a2 2 0 01-2 2H4a2 2 0 01-2-2V8a2 2 0 012-2z" />
              </svg>
            </span>
            <label htmlFor="email" className="sr-only">Correo electrónico</label>
            <Input
              id="email"
              name="email"
              type="email"
              autoComplete="email"
              required
              placeholder="Correo electrónico"
              className="!border-0 !bg-transparent !text-slate-900 !placeholder:text-slate-400 !py-2.5 !px-4 focus:!border-0 focus:!ring-0"
              value={form.email}
              onChange={(e) => setForm((prev) => ({ ...prev, email: e.target.value }))}
            />
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="flex items-center overflow-hidden rounded-xl border border-white/40 bg-white/90 text-slate-900 shadow-sm">
              <span className="flex h-11 w-11 items-center justify-center bg-panel text-white/80">
                <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M16 10V8a4 4 0 00-8 0v2" />
                  <rect x="5" y="10" width="14" height="10" rx="2" ry="2" strokeWidth="1.6" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M12 14v3" />
                </svg>
              </span>
              <label htmlFor="password" className="sr-only">Contraseña</label>
              <Input
                id="password"
                name="password"
                type="password"
                autoComplete="new-password"
                required
                placeholder="Contraseña"
                className="!border-0 !bg-transparent !text-slate-900 !placeholder:text-slate-400 !py-2.5 !px-4 focus:!border-0 focus:!ring-0"
                value={form.password}
                onChange={(e) => setForm((prev) => ({ ...prev, password: e.target.value }))}
              />
            </div>

            <div className="flex items-center overflow-hidden rounded-xl border border-white/40 bg-white/90 text-slate-900 shadow-sm">
              <span className="flex h-11 w-11 items-center justify-center bg-panel text-white/80">
                <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M16 10V8a4 4 0 00-8 0v2" />
                  <rect x="5" y="10" width="14" height="10" rx="2" ry="2" strokeWidth="1.6" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.6" d="M12 14v3" />
                </svg>
              </span>
              <label htmlFor="password_confirmation" className="sr-only">Confirmar contraseña</label>
              <Input
                id="password_confirmation"
                name="password_confirmation"
                type="password"
                autoComplete="new-password"
                required
                placeholder="Confirmar contraseña"
                className="!border-0 !bg-transparent !text-slate-900 !placeholder:text-slate-400 !py-2.5 !px-4 focus:!border-0 focus:!ring-0"
                value={form.password_confirmation}
                onChange={(e) => setForm((prev) => ({ ...prev, password_confirmation: e.target.value }))}
              />
            </div>
          </div>

          <div className="space-y-2">
            <p className="text-sm font-medium text-slate-700 dark:text-white/80">Rol</p>

            <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
              <button
                type="button"
                onClick={() => setForm((prev) => ({ ...prev, role: 'merchant' }))}
                aria-pressed={form.role === 'merchant'}
                className={`rounded-xl border px-4 py-2.5 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-400/60 ${
                  form.role === 'merchant'
                    ? 'border-brand-400/80 bg-brand-300 !text-ink shadow-sm'
                    : 'border-white/40 bg-white/90 !text-ink hover:bg-white'
                }`}
              >
                Comerciante
              </button>

              <button
                type="button"
                onClick={() => setForm((prev) => ({ ...prev, role: 'client' }))}
                aria-pressed={form.role === 'client'}
                className={`rounded-xl border px-4 py-2.5 text-sm font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-400/60 ${
                  form.role === 'client'
                    ? 'border-brand-400/80 bg-brand-300 !text-ink shadow-sm'
                    : 'border-white/40 bg-white/90 !text-ink hover:bg-white'
                }`}
              >
                Cliente
              </button>
            </div>

            <Select
              id="role"
              name="role"
              value={form.role}
              onChange={(e) => setForm((prev) => ({ ...prev, role: e.target.value }))}
              className="sr-only"
            >
              <option value="merchant">Comerciante</option>
              <option value="client">Cliente</option>
            </Select>
          </div>
        </div>

        {error && <div className="text-red-600 dark:text-red-200 text-sm">{error}</div>}

        <Button
          type="submit"
          className="w-full inline-flex items-center justify-center rounded-xl !bg-gradient-to-r from-brand-500 to-brand-600 px-4 py-2.5 text-sm font-semibold !text-white shadow-lg shadow-brand-600/30 hover:from-brand-600 hover:to-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/70 focus-visible:ring-offset-0 transition"
          loading={loading}
        >
          {loading ? (
            <span className="flex items-center gap-2">
              <svg className="animate-spin h-4 w-4 text-white" viewBox="0 0 24 24" fill="none">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
              </svg>
              Creando...
            </span>
          ) : (
            <span>Crear cuenta</span>
          )}
        </Button>

        <p className="text-center text-sm text-slate-600 dark:text-white/70">
          ¿Ya tienes cuenta?
          <Link to="/login" className="text-slate-900 dark:text-white font-semibold hover:opacity-90">
            {' '}
            Inicia sesión
          </Link>
        </p>
      </form>
    </div>
  )
}
