// src/components/ui/Button.vue
<template>
  <button
    :class="buttonClass"
    v-bind="$attrs"
    @click="$emit('click', $event)"
  >
    <slot />
  </button>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  variant: {
    type: String,
    default: 'default',
  },
  size: {
    type: String,
    default: 'default',
  },
})

const buttonClass = computed(() => {
  const baseClasses = 'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-semibold ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/35 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50'
  const variantClasses = {
    default: 'bg-primary text-primary-foreground hover:bg-primary/90',
    destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
    outline: 'border border-input bg-transparent hover:bg-secondary hover:text-foreground',
    secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
    ghost: 'hover:bg-secondary hover:text-foreground',
    link: 'text-primary underline-offset-4 hover:underline',
  }
  const sizeClasses = {
    default: 'h-10 px-4 py-2',
    sm: 'h-9 px-3',
    lg: 'h-11 px-8',
    icon: 'h-10 w-10',
  }
  return [
    baseClasses,
    variantClasses[props.variant] || variantClasses.default,
    sizeClasses[props.size] || sizeClasses.default,
  ].join(' ')
})
</script>

<style scoped>
/* Add any additional styles if needed */
</style>

// comercio-plus-frontend/src/components/ui/button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react'

const variants = {
  primary:
    'border border-brand-500 bg-brand-500 text-white shadow-lg shadow-brand-500/30 hover:border-brand-600 hover:bg-brand-600',
  secondary:
    'border border-slate-200 bg-white text-slate-900 shadow-sm hover:border-slate-300 hover:bg-slate-50 dark:border-white/15 dark:bg-white/10 dark:text-white dark:hover:border-white/25 dark:hover:bg-white/15',
  outline:
    'border border-slate-300 bg-transparent text-slate-800 hover:border-slate-400 hover:bg-slate-900/5 dark:border-white/20 dark:text-slate-100 dark:hover:border-white/35 dark:hover:bg-white/10',
  ghost:
    'border border-transparent bg-transparent text-slate-700 hover:bg-slate-900/5 hover:text-slate-900 dark:text-slate-100 dark:hover:bg-white/10 dark:hover:text-white',
  danger:
    'border border-red-500 bg-red-500 text-white shadow-lg shadow-red-500/25 hover:border-red-600 hover:bg-red-600',
} as const

export type ButtonVariant = keyof typeof variants

const baseButtonClasses =
  'inline-flex items-center justify-center gap-2 rounded-xl px-5 py-2.5 text-[13px] font-semibold transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500/40 focus-visible:ring-offset-2 focus-visible:ring-offset-transparent sm:text-[14px]'

type Props = ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: ButtonVariant
  loading?: boolean
  children: ReactNode
}

export const buttonVariants = (variant: ButtonVariant = 'primary', className = '') =>
  `${baseButtonClasses} ${variants[variant]} disabled:cursor-not-allowed disabled:opacity-50 ${className}`.trim()

export default function Button({
  variant = 'primary',
  loading = false,
  className = '',
  children,
  ...props
}: Props) {
  return (
    <button
      className={buttonVariants(variant, className)}
      disabled={loading || props.disabled}
      {...props}
    >
      {children}
    </button>
  )
}
